# Generated by Django 2.2.5 on 2021-07-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='category',
        ),
        migrations.AddField(
            model_name='categoria',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tienda.Producto'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
