# Generated by Django 2.2.5 on 2021-07-05 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_auto_20210705_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='product',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tienda.Categoria'),
        ),
    ]
