# Generated by Django 2.2.5 on 2021-07-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_auto_20210705_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='price',
            new_name='precio',
        ),
    ]
