# Generated by Django 2.2.5 on 2021-07-06 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tienda', '0004_auto_20210705_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tienda.Producto'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='user',
            field=models.OneToOneField(default= 1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
