# Generated by Django 2.2.5 on 2021-07-06 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0009_auto_20210706_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
