# Generated by Django 2.2.5 on 2021-07-06 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0010_auto_20210706_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
