# Generated by Django 2.2.5 on 2021-07-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0012_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(to='Tienda.Producto'),
        ),
    ]
