# Generated by Django 2.2.5 on 2021-07-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0014_auto_20210707_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
